### ISSUE TITLE
[RFE] Add cosign validation on sync

### ISSUE THREAD

**Issue by Daemonslayer2048** [hauler-dev/hauler#153]
**Is your feature request related to a problem? Please describe.**
Verifying images as they are collected would be preferable, this would allow a user to "trust" the images pulled into the store at the time of sync. This would prevent the end user from needing to verify either manually or via some other process, script, etc. 

**Describe the solution you'd like**
A cosign verify of each image (if possible) as it is synced to the store.  

**Describe alternatives you've considered**
The main idea I have come across is pulling images and pushing to a custom or temporary registry, verifying all images in that registry, then pulling from the verified registry into the Hauler store. This is obviously a cumbersome process. 

**Additional context**
It seems to me there are two options for how the hauler manifest could change:  
__Option 1:__  
Below is option one. The idea of option one is to allow a key to apply to an entire manifest of images, I think this would work, however, if the manifest is just one large collection of images from multiple vendors a single key would not work. 
```yaml
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: longhorn-images
  key: <key url>
spec:
  images:
    - name: longhornio/csi-attacher:v4.2.0
    - name: longhornio/csi-provisioner:v3.4.1
``` 

__Option 2:__  
Below is option 2, it resolves the issue in option one if a user wants to use many images from different vendors who would have different keys, but as you can see repeating the key possibly dozens of times would be cumbersome and difficult to keep human readable. 
```yaml
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: longhorn-images
spec:
  images:
    - name: longhornio/csi-attacher:v4.2.0
      key: <key url>
    - name: longhornio/csi-provisioner:v3.4.1
      key: <key url>
```

__Option 3:__  
Finally option 3, this would be the least opinionated option. The `.metadata.key` field could be used as a default key to be used on all images, but then overwritten if a key field is set on the image.  
```
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: longhorn-images
  key: <key 1 url>
spec:
  images:
    - name: longhornio/csi-attacher:v4.2.0
      key: <key 2 url> 
    - name: longhornio/csi-provisioner:v3.4.1
    - name: longhornio/csi-resizer:v1.7.0
```
