### ISSUE TITLE
[BUG] Chart Username and Password are not working

### ISSUE THREAD

**Issue by clemenko** [hauler-dev/hauler#190]
**Environmental Info:**
67 degrees and overcast

**Hauler Version:**
1.0.0.0.0.0.0

**System CPU architecture, OS, and Version:**
* 

**Describe the bug:**
the `hauler store sync` does not accept `--username` and `--password` fields for helm charts. 

**Steps To Reproduce:**
```
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: rancher-charts
spec:
  charts:
    - name: rancher
      repoURL: https://releases.rancher.com/server-charts/latest
      version: v2.8.2
      username: bob
      password: denver
```

**Expected behavior:**
it work?

**Actual behavior:**
it not work

**Additional context / logs:**
kitten photo
![1440](https://github.com/rancherfederal/hauler/assets/3177276/f5752c0e-a9f1-4149-9778-d0ea802f281d)
