### ISSUE TITLE
[BUG] Tilde (~) seems to be an invalid character for local files

### ISSUE THREAD

**Issue by mddamato** [hauler-dev/hauler#275]
**Environmental Info:**

Linux 6aa12afc0914 5.15.49-linuxkit-pr #1 SMP Thu May 25 07:17:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Hauler Version:**

1.0.4

**Describe the Bug:**

local files that contain a tilde "~" are not accepted.

**Steps to Reproduce:**

```bash
curl -LO https://rpm.rancher.io/rke2/stable/1.27/centos/8/x86_64/rke2-server-1.27.1~rke2r1-0.el8.x86_64.rpm
```

```yaml
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: hauler-content-files-example
spec:
  files:
    - path: rke2-server-1.27.1~rke2r1-0.el8.x86_64.rpm
      name: packages/rke2-server-1.27.1~rke2r1-0.el8.x86_64.rpm
```

**Expected Behavior:**

file downloaded, stored

**Actual Behavior:**

error message

```
2024-07-26 16:58:18 ERR could not parse reference: packages/rke2-server-1.27.1~rke2r1-0.el8.x86_64.rpm
```
