### ISSUE TITLE
[BUG] ingress-nginx charts fail to be stored

### ISSUE THREAD

**Issue by PrymalInstynct** [hauler-dev/hauler#362]
**Environmental Info:**

- Linux mini01.domain.local 6.11.6-arch1-1  SMP PREEMPT_DYNAMIC Fri, 01 Nov 2024 03:30:41 +0000 x86_64 GNU/Linux

**Hauler Version:**

- GitVersion:    1.0.8
- GitCommit:     e42f72f
- GitTreeState:  clean
- BuildDate:     2024-09-04T18:15:19Z
- GoVersion:     go1.21.13
- Compiler:      gc
- Platform:      linux/amd64

**Describe the Bug:**

- I am trying to add the ingress-nginx helm chart to the Hauler store but it is failing showing the error that the `Chart.yaml file is missing`

**Steps to Reproduce:**

1. Create Hauler Manifest
```
### -----------------------------------------
### Ingress Nginx
### -----------------------------------------
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: ingress-nginx-images
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    - name: registry.k8s.io/ingress-nginx/controller:v1.11.3
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: ingress-nginx-charts
spec:
  charts:
    - name: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      version: 4.11.3
```
2. Run the hauler sync command
```
hauler store sync --files cluster-hauler-manifest.yaml`
```
3. Get the Error
```
Error: Chart.yaml file is missing
Usage:
  hauler store sync [flags]
```
4. Try the Hauler store add command instead
```
hauler store add chart ingress-nginx --repo https://kubernetes.github.io/ingress-nginx/ --version "4.11.3"
``` 
5. Get the same error as above

**Expected Behavior:**

- The Chart is added successfully to the Hauler Store

**Actual Behavior:**

- See Above

**Additional Context:**

- The Hauler Manifest I created contains more items then just ingress-nginx and is successfully adding other charts example below

```
### -----------------------------------------
### Datashim
### -----------------------------------------
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: datashim-images
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    - name: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
    - name: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
    - name: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
    - name: quay.io/datashim-io/dataset-operator:0.4.0
    - name: quay.io/datashim-io/csi-nfs:f590a7f
    - name: quay.io/datashim-io/csi-s3:f590a7f
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: datashim-charts
spec:
  charts:
    - name: datashim-charts
      repoURL: https://datashim-io.github.io/datashim
      version: 0.4.0
```
