### ISSUE TITLE
[BUG] Regression of 'continue pull after error' in v1.1.1

### ISSUE THREAD

**Issue by HoustonDad** [hauler-dev/hauler#381]
**Environmental Info:**
```
Linux hauler 5.15.0-125-generic #135-Ubuntu SMP Fri Sep 27 13:53:58 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Hauler Version:**
- v1.1.1

**Describe the Bug:**
- We previously adjusted code in v1.1.0 that will 'continue pull after error'. This has regressed in v1.1.1

**Steps to Reproduce:**
1. Install Hauler v1.1.0
```
curl -sfL https://get.hauler.dev | HAULER_VERSION=1.1.0 bash
```
2. Minify a manifest with an image that you know will fail:
```
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: carbide-rancher-images
spec:
  images:
    - name: rgcrprod.azurecr.us/rancher/mirrored-prometheus-operator-prometheus-operator:v0.72.0
    - name: rgcrprod.azurecr.us/rancher/mirrored-prometheus-prometheus:v2.50.1
    - name: rgcrprod.azurecr.us/rancher/mirrored-prometheus-windows-exporter:0.25.1
    - name: rgcrprod.azurecr.us/rancher/mirrored-sig-storage-csi-attacher:v4.2.0
    - name: rgcrprod.azurecr.us/rancher/mirrored-sig-storage-csi-attacher:v4.3.0
    - name: rgcrprod.azurecr.us/rancher/mirrored-sig-storage-csi-attacher:v4.5.0
```
3. Run manifest and see that it continues with manifest after failing on 'rancher/mirrored-prometheus-windows-exporter'
```
hauler store sync --store tkt-7546-store -f rancher-manifest.yaml --key carbide-key.pub --platform linux/amd64
```
4. Upgrade Hauler to v1.1.1
```
curl -sfL https://get.hauler.dev | bash
```
5. Rerun same manifests and see that it Hauler stops the manifest after hitting 'rancher/mirrored-prometheus-windows-exporter'
```
hauler store sync --store tkt-7546-store -f rancher-manifest.yaml --key carbide-key.pub --platform linux/amd64
```

**Expected Behavior:**
- Hauler should continue on after that pull error

**Actual Behavior:**
- Hauler does NOT continue on after that pull error
