### ISSUE TITLE
[feature] Allow specification of target sync store in manifest file

### ISSUE THREAD

**Issue by mcarter-cyber** [hauler-dev/hauler#392]
**Is this Feature/Enhancement related to an Existing Problem? If so, please describe:**

- The target store for each manifest file is specified on the command line at time of sync, so when passing multiple files to the `hauler store sync` command, all files will have the same content store.

**Describe Proposed Solution(s):**

- Add a metadata attribute containing target content store, i.e.:

```yaml
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: hauler-files
  store: extras
spec:
  files:
    - path: https://github.com/hauler-dev/hauler/releases/download/v1.1.1/hauler_1.1.1_linux_amd64.tar.gz
      name: hauler-linux-amd64.tar.gz
```

**Describe Possible Alternatives:**

- Store could be set via an annotation instead, i.e.:
```yaml
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: hauler-files
  annotations:
    hauler.dev/store: <store>
spec:
  files:
    - path: https://github.com/hauler-dev/hauler/releases/download/v1.1.1/hauler_1.1.1_linux_amd64.tar.gz
      name: hauler-linux-amd64.tar.gz
```

**Additional Context:**

- N/A
