### ISSUE TITLE
Define `Driver` API

### ISSUE THREAD

**Issue by joshrwolf** [hauler-dev/hauler#53]
Define what the `Driver` api should look like, initial ideas below:

```yaml
apiVersion: driver.hauler.cattle.io/v1alpha1
kind: Driver
metadata:
  name: bleh
spec:
  version: 0.1.0
  image:
    collect: my-collector-image:v1
    extract: my-extractor-image:v1
```
