### ISSUE TITLE
Ensure local only charts can be packaged

### ISSUE THREAD

**Issue by joshrwolf** [hauler-dev/hauler#99]
Currently the `charts` content api allows for fetching remote only charts.  Modify this slightly to ensure local charts can also be packaged just as easily.

IS:

```yaml
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: mychart
spec:
  charts:
    - name: loki
      repoURL: https://grafana.github.io/helm-charts
      version: #
```

PROPOSED:

```yaml
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: mychart
spec:
  charts:
    - name: loki
      repoURL: https://grafana.github.io/helm-charts
      version: #
      # optional path variable that take precedence over name/repoURL/version
      path: 
  # should understand folders with Chart.yaml
   - path: path/to/local/chart 
  # and path to archived chart
   - path: path/to/archived/chart.tgz
```
